import type { Metadata } from "next";
import {
  absoluteUrl,
  getSiteUrl,
  truncateMeta,
} from "@/lib/site-url";
import { buildHreflangLanguages } from "@/lib/seo/hreflang";
import { defaultLocale } from "@/lib/i18n/config";
import { localizePath } from "@/lib/i18n/locale-path";
import { toOgLocale } from "@/lib/i18n/og-locale";
import type { Locale } from "@/lib/i18n/config";

export { absoluteUrl, getSiteUrl, truncateMeta };

/**
 * Default social card.
 *
 * This route is generated by Next.js and is safe to use
 * as the default image for pages that do not have a custom image.
 */
export const DEFAULT_OG_PATH = "/opengraph-image";

/**
 * Remove HTML and normalize whitespace before using content
 * in metadata or structured data.
 */
export function stripHtml(text: string | null | undefined): string {
  return String(text || "")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Map application employment types to schema.org JobPosting values.
 */
export function toSchemaEmploymentType(
  raw: string | null | undefined
): string {
  const value = String(raw || "")
    .toLowerCase()
    .replace(/[_-]+/g, " ")
    .trim();

  if (!value) return "FULL_TIME";

  if (value.includes("part")) return "PART_TIME";

  if (
    value.includes("contract") ||
    value.includes("freelance") ||
    value.includes("contractor")
  ) {
    return "CONTRACTOR";
  }

  if (
    value.includes("temp") ||
    value.includes("temporary")
  ) {
    return "TEMPORARY";
  }

  if (value.includes("intern")) return "INTERN";

  if (value.includes("volunteer")) return "VOLUNTEER";

  if (value.includes("full")) return "FULL_TIME";

  return "OTHER";
}

/**
 * Serialize a JSON-LD object for safe embedding inside a
 * <script type="application/ld+json"> tag via dangerouslySetInnerHTML.
 *
 * Escapes characters that could otherwise break out of the script
 * context or be used for XSS (</script>, <!--, line/paragraph
 * separators that some browsers treat specially in inline scripts).
 */
export function jsonLdScript(data: unknown): string {
  return JSON.stringify(data)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/&/g, "\\u0026")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

/**
 * Normalize a public pathname.
 *
 * This function intentionally removes any existing locale prefix
 * before generating the canonical URL.
 */
export function normalizeSeoPath(pathname: string): string {
  const raw = pathname.startsWith("/")
    ? pathname
    : `/${pathname}`;

  return raw.replace(/^\/(en|es|ar|fa|hi|fr|de)(?=\/|$)/i, "") || "/";
}

/**
 * Build a fully localized public metadata object.
 *
 * IMPORTANT:
 * - English uses the unprefixed URL.
 * - Other locales use /{locale}/...
 * - hreflang is generated from the unprefixed path.
 * - canonical points to the current locale.
 */
export function buildPublicMetadata(opts: {
  title: string;
  description: string;
  path: string;
  image?: string | null;
  index?: boolean;
  type?: "website" | "article" | "profile";
  locale?: Locale;
  hreflang?: boolean;
}): Metadata {
  const locale = opts.locale || defaultLocale;
  const path = normalizeSeoPath(opts.path);

  const canonicalPath = localizePath(path, locale);
  const canonicalUrl = absoluteUrl(canonicalPath);

  const image =
    opts.image && /^https?:\/\//i.test(opts.image)
      ? opts.image
      : absoluteUrl(DEFAULT_OG_PATH);

  const shouldIndex = opts.index !== false;
  const shouldAddHreflang =
    opts.hreflang !== false && shouldIndex;

  const metadata: Metadata = {
    title: opts.title,
    description: truncateMeta(opts.description, 160),

    alternates: {
      canonical: canonicalUrl,
      ...(shouldAddHreflang
        ? {
            languages: buildHreflangLanguages(path),
          }
        : {}),
    },

    openGraph: {
      type: opts.type || "website",
      url: canonicalUrl,
      locale: toOgLocale(locale),
      title: opts.title,
      description: truncateMeta(opts.description, 160),
      siteName: "Global Job Matching",
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: opts.title,
        },
      ],
    },

    twitter: {
      card: "summary_large_image",
      title: opts.title,
      description: truncateMeta(opts.description, 160),
      images: [image],
    },

    robots: shouldIndex
      ? {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
          },
        }
      : {
          index: false,
          follow: false,
        },
  };

  return metadata;
}
